title: "Session 1: Year 8 'Relevance' training – Introduction"
hero_image: images/introduction1.png
description: Session 1 of the online training course introduces teachers to the intervention and some of the resources for the Year 8 'Relevance' Teaching Approach trial
version: 4
listed: false
copyedit: false
last_tested: "2020-08-19"
steps:
  - title: Introduction to the course
  - title: The Gender Balance in Computing (GBIC) programme
  - title: The Teaching Approach trial
  - title: The 'Relevance' approach
  - title: Why would making learning relevant be good for girls?
  - title: Data collection using the online survey
  - title: Additional information and guidance
  - title: Summary of Session 1
